#이름 : 값
#  이름 :
#    이름 : 값
#services:
#  컨테이너이름:
# docker compose up -d (d는 백그라운드 실행 원할 경우)
services:
  next-blog:
    image: next-blog:1.0.0
    ports:
      - 3000:3000
    networks:
      mynet1:
        ipv4_address: 172.18.0.2
    environment:
      TZ: "Asia/Seoul"
    restart: always

  nginx:
    image: nginx:1
    ports:
      - 80:80
    networks:
      mynet1:
        ipv4_address: 172.18.0.3
    environment:
      TZ: "Asia/Seoul"
    depends_on:
      - next-blog
    restart: always

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=Asia/Seoul
    volumes:
      - vol_post:/var/lib/postgresql/data
    restart: always

networks:
  mynet1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
volumes:
  vol_post:
#    external: true  <<  기존에 있던거 갖다 쓰려면